name: Run Gradle on PRs
on:
    push:
        branches: [ test_cache_ro ]
jobs:
    populate_cache:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: corretto
                  java-version: 17
            - name: Build
              run: |
                  ./gradlew :help
                  mkdir cache-ro
                  cp -r ~/.gradle/caches/modules-2 cache-ro
              env:
                  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
            - name: Cache the Generated File
              uses: actions/cache@v3
              with:
                path: cache-ro
                key: gradle-cache-file-03

    consume_cache:
        needs: ["populate_cache"]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: corretto
                  java-version: 17
            - name: Get Cache
              uses: actions/cache@v3
              with:
                 path: cache-ro
                 key: gradle-cache-file-03
            - name: Build
              run: |
                  export GRADLE_RO_DEP_CACHE=$PWD/cache-ro
                  ./gradlew :help
              env:
                  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
