name: Build

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true

jobs:
    iterations:
        name: Generate versions
        runs-on: ubuntu-latest
        steps:
            -   id: calculate_iterations
                run: |
                    iterations=" ["
                    for i in {1..1}
                    do
                      if [ $i == 1 ]
                      then
                        iterations="$iterations \"$i\""
                      else
                        iterations="$iterations  , \"$i\""
                      fi
                    done
                    iterations="$iterations ]"
                    echo "iterations=$iterations" >> $GITHUB_OUTPUT
                    echo $GITHUB_OUTPUT
        outputs:
            iterations: ${{ steps.calculate_iterations.outputs.iterations }}

    test_and_apk:
        needs: [ iterations ]
        strategy:
            matrix:
                workers:  [1,2,3,4]
                runs: ${{ fromJson(needs.iterations.outputs.iterations) }}

        name: "Local tests and APKs"
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        timeout-minutes: 60

        steps:
            -   name: Collect Workflow Telemetry
                uses: catchpoint/workflow-telemetry-action@v2

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Install stress tool
                run: sudo apt-get install -y stress

            -   name: Start CPU load in the background
                run: stress --io ${{ matrix.workers }} --cpu ${{ matrix.workers }} --timeout 720 &

            -   name: Assemble Release
                run: |
                    ./gradlew clean assembleDebug -Dscan.tag.11new-fio-experiment  -Dscan.tag.itops-${{ matrix.workers }}- -Dscan.tag.assembleDebug
                env:
                    GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}

